name: BB PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

# jobs:
#   run-gleam-and-process-pr:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup Gleam and Process PR
#         uses: 0v00/kmt@master
#         env:
#           TEST_SECRET: ${{ secrets.TEST_SECRET }}
#         with:
#           pr_id: ${{ github.event.pull_request.number }}

jobs:
  run-bb-and-process-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup BB and Process PR
        uses: tzafrirben/babashka-docker-action@v1
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        with:
          bb_src: 'https://github.com/0v00/kmt-clj/blob/master/kmt.clj'
          bb_args: ${{ github.event.pull_request.number }}