name: BB PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

# jobs:
#   run-gleam-and-process-pr:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup Gleam and Process PR
#         uses: 0v00/kmt@master
#         env:
#           TEST_SECRET: ${{ secrets.TEST_SECRET }}
#         with:
#           pr_id: ${{ github.event.pull_request.number }}

jobs:
  run-bb-and-process-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup BB and Process PR
        id: bb_script
        uses: tzafrirben/babashka-docker-action@v1.1
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        with:
          bb_src: 'src/kmt.clj'
          bb_args: ${{ github.event.pull_request.number }}
      - name: Get the bb script output
        run: echo "${{ steps.bb_script.outputs.bb_out }}"
      - name: Create PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bb_output: ${{ steps.bb_script.outputs.bb_out }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Babashka script output:\n\n${core.getInput('bb_output')}`
            })