name: Gleam PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-gleam-and-process-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gleam and Process PR
        uses: 0v00/kmt@master
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        with:
          pr_id: ${{ github.event.pull_request.number }}